import React from "react";
import { ComponentMeta, ComponentStory } from "@storybook/react";
import { SettingsSvg, DashboardSvg, MenuSvg, TokensSvg, LeftSvg, OsmosisSvg, OverviewSvg, PoolSvg } from "./";
declare const _default: ComponentMeta<(props: React.SVGProps<SVGSVGElement>) => JSX.Element>;
export default _default;
export declare const Osmosis: ComponentStory<typeof OsmosisSvg>;
export declare const Dashboard: ComponentStory<typeof DashboardSvg>;
export declare const Left: ComponentStory<typeof LeftSvg>;
export declare const Menu: ComponentStory<typeof MenuSvg>;
export declare const Overview: ComponentStory<typeof OverviewSvg>;
export declare const Pools: ComponentStory<typeof PoolSvg>;
export declare const Tokens: ComponentStory<typeof TokensSvg>;
export declare const Settings: ComponentStory<typeof SettingsSvg>;
