import defaultTheme from "tailwindcss/defaultTheme";

export const fontSize = {
	xxs: "0.5rem",
	xs: "0.75rem",
	sm: "0.875rem",
	base: "1rem",
	lg: "1.25rem",
	xl: "1.5rem",
	"2xl": "2.25rem",
	"3xl": "3rem",
	"4xl": "3.75rem",
	"5xl": "6rem",
	h1: ["6rem", { lineHeight: "7rem", letterSpacing: "-1.5px" }],
	h2: ["3.75rem", { lineHeight: "4.5rem", letterSpacing: "-0.5px" }],
	h3: ["3rem", { lineHeight: "3.5rem", letterSpacing: "0" }],
	h4: ["2.25rem", { lineHeight: "2.25rem", letterSpacing: "0" }],
	h5: ["1.5rem", { lineHeight: "2rem", letterSpacing: "0.18px" }],
	h6: ["1.25rem", { lineHeight: "1.5rem", letterSpacing: "0.15px" }],
	subtitle1: ["1rem", { lineHeight: "1.5rem", letterSpacing: "0.15px" }],
	subtitle2: ["0.875rem", { lineHeight: "1.5rem", letterSpacing: "0.1px" }],
	body1: ["1rem", { lineHeight: "1.5rem", letterSpacing: "0.5px" }],
	body2: ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "0.25px" }],
	button: ["0.875rem", { lineHeight: "1rem", letterSpacing: "0" }],
	caption: ["0.75rem", { lineHeight: "0.875rem", letterSpacing: "0.4px" }],
	overline: ["0.625rem", { lineHeight: "1rem", letterSpacing: "2.5px" }],
};

export const fontFamily = {
	h1: ["Poppins", "ui-sans-serif", "system-ui"],
	h2: ["Poppins", "ui-sans-serif", "system-ui"],
	h3: ["Poppins", "ui-sans-serif", "system-ui"],
	h4: ["Poppins", "ui-sans-serif", "system-ui"],
	h5: ["Poppins", "ui-sans-serif", "system-ui"],
	h6: ["Poppins", "ui-sans-serif", "system-ui"],
	subtitle1: ["Inter", "ui-sans-serif", "system-ui"],
	subtitle2: ["Inter", "ui-sans-serif", "system-ui"],
	body1: ["Inter", "ui-sans-serif", "system-ui"],
	body2: ["Inter", "ui-sans-serif", "system-ui"],
	button: ["Inter", "ui-sans-serif", "system-ui"],
	caption: ["Inter", "ui-sans-serif", "system-ui"],
	overline: ["Poppins", "ui-sans-serif", "system-ui"],
};

export const fontWeight = {
	...defaultTheme.fontWeight,
	h1: 600,
	h2: 600,
	h3: 600,
	h4: 600,
	h5: 600,
	h6: 600,
	subtitle1: 600,
	subtitle2: 400,
	body1: 400,
	body2: 400,
	button: 600,
	caption: 400,
	overline: 400,
};
